In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [2]:
"""
The dataset consists of age, sex, BMI(body mass index), children, 
smoker and region feature, which are independent and charge as a dependent feature.
We will predict individual medical costs billed by health insurance.
"""
df = pd.read_csv('insurance.csv')
print(df)

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [3]:
print('\nNumber of rows and columns in the data set: ',df.shape)

Number of rows and columns in the data set:  (1338, 7)

In [4]:
df.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [5]:
df.describe()

               age          bmi     children      expenses
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.665471     1.094918  13270.422414
std      14.049960     6.098382     1.205493  12110.011240
min      18.000000    16.000000     0.000000   1121.870000
25%      27.000000    26.300000     0.000000   4740.287500
50%      39.000000    30.400000     1.000000   9382.030000
75%      51.000000    34.700000     2.000000  16639.915000
max      64.000000    53.100000     5.000000  63770.430000

In [6]:
# Check for missing value
missing_values = df.isnull().sum()
print(missing_values)  # This will show the count of missing values in each column

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [7]:
# ------ features and output (label) ------
input_df = df.drop(columns='expenses')
target_df = df.expenses

In [8]:
input_df

      age     sex   bmi  children smoker     region
0      19  female  27.9         0    yes  southwest
1      18    male  33.8         1     no  southeast
2      28    male  33.0         3     no  southeast
3      33    male  22.7         0     no  northwest
4      32    male  28.9         0     no  northwest
...   ...     ...   ...       ...    ...        ...
1333   50    male  31.0         3     no  northwest
1334   18  female  31.9         0     no  northeast
1335   18  female  36.9         0     no  southeast
1336   21  female  25.8         0     no  southwest
1337   61  female  29.1         0    yes  northwest

[1338 rows x 6 columns]

In [9]:
target_df

0       16884.92
1        1725.55
2        4449.46
3       21984.47
4        3866.86
          ...
1333    10600.55
1334     2205.98
1335     1629.83
1336     2007.95
1337    29141.36
Name: expenses, Length: 1338, dtype: float64

In [11]:
from sklearn.preprocessing import LabelEncoder

# Define the columns for encoding
columns_to_encode = ["sex", "smoker", "region"]  # Replace with your column names

# Create a LabelEncoder object
le = LabelEncoder()

# Loop through each column and encode
for col in columns_to_encode:
  input_df[col] = le.fit_transform(input_df[col])

In [12]:
input_df

      age  sex   bmi  children  smoker  region
0      19    0  27.9         0       1       3
1      18    1  33.8         1       0       2
2      28    1  33.0         3       0       2
3      33    1  22.7         0       0       1
4      32    1  28.9         0       0       1
...   ...  ...   ...       ...     ...     ...
1333   50    1  31.0         3       0       1
1334   18    0  31.9         0       0       0
1335   18    0  36.9         0       0       2
1336   21    0  25.8         0       0       3
1337   61    0  29.1         0       1       1

[1338 rows x 6 columns]

In [13]:
from sklearn.preprocessing import MinMaxScaler

# Specify the column name for scaling
column_name = "expenses"  # Replace with the actual column name

# Create a MinMaxScaler object
scaler = MinMaxScaler()

# Fit the scaler on the column data (learn range)
scaler.fit(df[[column_name]])  # Double square brackets to select a DataFrame

# Transform the column data using the fitted scaler
scaled_data = scaler.transform(df[[column_name]])

In [14]:
target_df = scaled_data

In [15]:
target_df

array([[0.25161073],
       [0.00963598],
       [0.05311519],
       ...,
       [0.00810809],
       [0.01414366],
       [0.44724875]])

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(input_df, target_df, test_size=0.2, random_state=20)

In [ ]:
X_test

In [ ]:
#For linear regression, Y=the value we want to predict
#X= all independent variables upon which Y depends. 
#3 steps for linear regression....
#Step 1: Create the instance of the model
#Step 2: .fit() to train the model or fit a linear model
#Step 3: .predict() to predict Y for given X values.

In [ ]:
from sklearn.linear_model import LinearRegression

#object
reg = LinearRegression()
#fit
reg.fit(X_train, Y_train)

In [ ]:
prediction_test = reg.predict(X_test)

In [ ]:
prediction_test

In [ ]:
from sklearn.metrics import mean_absolute_error 
from sklearn.metrics import mean_squared_error 
from sklearn.metrics import median_absolute_error
import matplotlib.pyplot as plt

In [ ]:
prediction_test = reg.predict(X_test)    
print(Y_test, prediction_test)
#----------------------------------------------------
#Calculating Mean Absolute Error
MAEValue = mean_absolute_error(Y_test, prediction_test, multioutput='uniform_average') # it can be raw_values
print('Mean Absolute Error Value is : ', MAEValue)

#----------------------------------------------------
#Calculating Mean Squared Error
MSEValue = mean_squared_error(Y_test, prediction_test, multioutput='uniform_average') # it can be raw_values
print('Mean Squared Error Value is : ', MSEValue)

#----------------------------------------------------
#Calculating Median Squared Error
MdSEValue = median_absolute_error(Y_test, prediction_test)
print('Median Squared Error Value is : ', MdSEValue )

In [ ]:
#Y_test_original = scaler.inverse_transform(Y_test)
prediction_test_original = scaler.inverse_transform(prediction_test)

In [ ]:
prediction_test_original