# Simple Linear Regression on Insurance DataSet

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as pltgit

In [63]:
"""
The dataset consists of age, sex, BMI(body mass index), children, 
smoker and region feature, which are independent and charge as a dependent feature.
We will predict individual medical costs billed by health insurance.
"""
df = pd.read_csv('insurance.csv')
print(df)

      age     sex   bmi  children smoker     region  expenses
0      19  female  27.9         0    yes  southwest  16884.92
1      18    male  33.8         1     no  southeast   1725.55
2      28    male  33.0         3     no  southeast   4449.46
3      33    male  22.7         0     no  northwest  21984.47
4      32    male  28.9         0     no  northwest   3866.86
...   ...     ...   ...       ...    ...        ...       ...
1333   50    male  31.0         3     no  northwest  10600.55
1334   18  female  31.9         0     no  northeast   2205.98
1335   18  female  36.9         0     no  southeast   1629.83
1336   21  female  25.8         0     no  southwest   2007.95
1337   61  female  29.1         0    yes  northwest  29141.36

[1338 rows x 7 columns]

In [64]:
print('\nNumber of rows and columns in the data set: ',df.shape)

Number of rows and columns in the data set:  (1338, 7)

In [65]:
df.head()

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [66]:
df.describe()

               age          bmi     children      expenses
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.665471     1.094918  13270.422414
std      14.049960     6.098382     1.205493  12110.011240
min      18.000000    16.000000     0.000000   1121.870000
25%      27.000000    26.300000     0.000000   4740.287500
50%      39.000000    30.400000     1.000000   9382.030000
75%      51.000000    34.700000     2.000000  16639.915000
max      64.000000    53.100000     5.000000  63770.430000

In [67]:
# Check for missing value
missing_values = df.isnull().sum()
print(missing_values)  # This will show the count of missing values in each column

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
expenses    0
dtype: int64

In [68]:
# ------ features and output (label) ------
input_df = df.drop(columns='expenses')
target_df = df.expenses

In [69]:
input_df

      age     sex   bmi  children smoker     region
0      19  female  27.9         0    yes  southwest
1      18    male  33.8         1     no  southeast
2      28    male  33.0         3     no  southeast
3      33    male  22.7         0     no  northwest
4      32    male  28.9         0     no  northwest
...   ...     ...   ...       ...    ...        ...
1333   50    male  31.0         3     no  northwest
1334   18  female  31.9         0     no  northeast
1335   18  female  36.9         0     no  southeast
1336   21  female  25.8         0     no  southwest
1337   61  female  29.1         0    yes  northwest

[1338 rows x 6 columns]

In [70]:
target_df

0       16884.92
1        1725.55
2        4449.46
3       21984.47
4        3866.86
          ...
1333    10600.55
1334     2205.98
1335     1629.83
1336     2007.95
1337    29141.36
Name: expenses, Length: 1338, dtype: float64

In [71]:
from sklearn.preprocessing import LabelEncoder

# Define the columns for encoding
columns_to_encode = ["sex", "smoker", "region"]  # Replace with your column names

# Create a LabelEncoder object
le = LabelEncoder()

# Loop through each column and encode
for col in columns_to_encode:
  input_df[col] = le.fit_transform(input_df[col])

In [72]:
input_df

      age  sex   bmi  children  smoker  region
0      19    0  27.9         0       1       3
1      18    1  33.8         1       0       2
2      28    1  33.0         3       0       2
3      33    1  22.7         0       0       1
4      32    1  28.9         0       0       1
...   ...  ...   ...       ...     ...     ...
1333   50    1  31.0         3       0       1
1334   18    0  31.9         0       0       0
1335   18    0  36.9         0       0       2
1336   21    0  25.8         0       0       3
1337   61    0  29.1         0       1       1

[1338 rows x 6 columns]

In [73]:
from sklearn.preprocessing import MinMaxScaler

# Specify the column name for scaling
column_name = "expenses"  # Replace with the actual column name

# Create a MinMaxScaler object
scaler = MinMaxScaler()

# Fit the scaler on the column data (learn range)
scaler.fit(df[[column_name]])  # Double square brackets to select a DataFrame

# Transform the column data using the fitted scaler
scaled_data = scaler.transform(df[[column_name]])

In [74]:
target_df = scaled_data

In [75]:
target_df

array([[0.25161073],
       [0.00963598],
       [0.05311519],
       ...,
       [0.00810809],
       [0.01414366],
       [0.44724875]], shape=(1338, 1))

In [76]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(input_df, target_df, test_size=0.2, random_state=20)

In [77]:
X_test

      age  sex   bmi  children  smoker  region
698    56    1  33.7         0       0       1
520    50    0  27.4         0       0       0
1144   50    1  32.3         2       0       3
908    63    1  39.8         3       0       3
559    19    1  35.5         0       0       1
...   ...  ...   ...       ...     ...     ...
851    61    1  32.3         2       0       1
109    63    1  35.1         0       1       2
941    50    0  46.1         1       0       2
600    18    0  39.2         0       0       2
865    40    1  29.9         2       0       3

[268 rows x 6 columns]

In [78]:
#For linear regression, Y=the value we want to predict
#X= all independent variables upon which Y depends. 
#3 steps for linear regression....
#Step 1: Create the instance of the model
#Step 2: .fit() to train the model or fit a linear model
#Step 3: .predict() to predict Y for given X values.

In [79]:
from sklearn.linear_model import LinearRegression

#object
reg = LinearRegression()
#fit
reg.fit(X_train, Y_train)

LinearRegression()

In [80]:
prediction_test = reg.predict(X_test)

In [81]:
prediction_test

array([[ 0.19258687],
       [ 0.14249682],
       [ 0.16874043],
       [ 0.26996671],
       [ 0.05583164],
       [ 0.01680437],
       [ 0.01610805],
       [ 0.17216084],
       [ 0.59441419],
       [ 0.16238444],
       [ 0.24228155],
       [ 0.4441166 ],
       [ 0.03405751],
       [ 0.19215979],
       [ 0.45755453],
       [ 0.13640801],
       [ 0.49433625],
       [ 0.17793333],
       [ 0.03074942],
       [ 0.15972318],
       [ 0.60433825],
       [ 0.11343601],
       [ 0.1677746 ],
       [ 0.01922353],
       [ 0.18341015],
       [ 0.08130202],
       [ 0.50697874],
       [ 0.18656138],
       [ 0.4400924 ],
       [ 0.17455682],
       [ 0.14386894],
       [ 0.027059  ],
       [ 0.59476365],
       [ 0.59860627],
       [ 0.21801824],
       [ 0.09452994],
       [ 0.04442156],
       [-0.00244583],
       [ 0.49103   ],
       [ 0.39714886],
       [ 0.17789106],
       [ 0.2433805 ],
       [ 0.01184841],
       [ 0.00082175],
       [ 0.19559552],
       [ 0.11840518],
       [ 0.15376558],
       [ 0.07644573],
       [ 0.59101557],
       [ 0.02002698],
       [ 0.17652447],
       [ 0.55117119],
       [ 0.1431047 ],
       [ 0.1656844 ],
       [ 0.09905279],
       [ 0.41859142],
       [ 0.12971309],
       [ 0.00831718],
       [ 0.07692683],
       [ 0.42811815],
       [ 0.42051566],
       [ 0.48532064],
       [ 0.18695644],
       [ 0.0936253 ],
       [ 0.14401024],
       [ 0.18448461],
       [ 0.2050103 ],
       [ 0.11283152],
       [ 0.57417527],
       [ 0.4899653 ],
       [ 0.16604722],
       [ 0.17865966],
       [ 0.35519167],
       [ 0.4729888 ],
       [ 0.16261622],
       [ 0.18117886],
       [ 0.15810239],
       [ 0.29035102],
       [ 0.05745162],
       [ 0.10936864],
       [ 0.1246613 ],
       [ 0.09869116],
       [ 0.48150943],
       [ 0.08009735],
       [ 0.63318933],
       [ 0.17325502],
       [ 0.08158596],
       [ 0.12867763],
       [ 0.49656205],
       [ 0.42687444],
       [ 0.21618037],
       [ 0.51761941],
       [ 0.55419351],
       [ 0.14646545],
       [ 0.04465527],
       [ 0.08652798],
       [ 0.10719687],
       [ 0.02833472],
       [-0.00626737],
       [ 0.14200998],
       [ 0.59757365],
       [ 0.12972525],
       [ 0.19294106],
       [ 0.05728397],
       [ 0.12374324],
       [ 0.11681755],
       [ 0.21379068],
       [ 0.43616518],
       [ 0.16976825],
       [ 0.23632502],
       [ 0.56740247],
       [ 0.18738352],
       [ 0.21082896],
       [ 0.06643177],
       [ 0.19234263],
       [ 0.05833265],
       [ 0.14879307],
       [ 0.44369628],
       [ 0.41054683],
       [ 0.14657048],
       [ 0.19909248],
       [ 0.19106638],
       [ 0.16294786],
       [ 0.10079225],
       [ 0.12879839],
       [ 0.09574497],
       [ 0.01082059],
       [ 0.03137103],
       [ 0.15972085],
       [ 0.18374569],
       [ 0.20820367],
       [ 0.1612426 ],
       [ 0.08467196],
       [ 0.62073169],
       [ 0.07565867],
       [ 0.12935417],
       [ 0.16831223],
       [ 0.06431882],
       [ 0.21298574],
       [ 0.2007559 ],
       [ 0.14441836],
       [ 0.17847335],
       [ 0.07510918],
       [ 0.41124818],
       [ 0.17101406],
       [ 0.08405256],
       [ 0.06814408],
       [ 0.43433757],
       [ 0.08353515],
       [ 0.24921887],
       [ 0.05810977],
       [ 0.06871932],
       [ 0.08052449],
       [ 0.14984591],
       [ 0.11450491],
       [ 0.11635147],
       [ 0.08166753],
       [ 0.03636322],
       [ 0.14746366],
       [ 0.03773168],
       [ 0.26520119],
       [ 0.0931771 ],
       [-0.03065093],
       [ 0.46216126],
       [ 0.1160533 ],
       [ 0.11243293],
       [ 0.02925602],
       [ 0.06231047],
       [ 0.07746733],
       [ 0.19150688],
       [ 0.08642379],
       [ 0.50072462],
       [ 0.18171013],
       [ 0.10025542],
       [ 0.60694295],
       [ 0.13184145],
       [ 0.01425549],
       [ 0.01120815],
       [ 0.10230298],
       [ 0.2123657 ],
       [ 0.18624826],
       [ 0.18461489],
       [ 0.6006383 ],
       [ 0.14959253],
       [ 0.19233267],
       [ 0.16809191],
       [ 0.11435018],
       [ 0.11823307],
       [ 0.60484816],
       [ 0.42491369],
       [ 0.13240906],
       [ 0.26013682],
       [ 0.23394487],
       [ 0.49043981],
       [ 0.10013227],
       [ 0.45130544],
       [-0.03724102],
       [ 0.40089987],
       [ 0.11558439],
       [ 0.16315865],
       [ 0.19623308],
       [ 0.18461219],
       [ 0.09934568],
       [ 0.19907622],
       [ 0.63355965],
       [ 0.0425384 ],
       [ 0.1728464 ],
       [ 0.23765954],
       [ 0.16131605],
       [ 0.07849522],
       [ 0.02067586],
       [ 0.18215069],
       [ 0.21233206],
       [ 0.07661784],
       [ 0.22287503],
       [-0.04857142],
       [ 0.42956525],
       [ 0.13002891],
       [ 0.27871311],
       [ 0.16459969],
       [ 0.21774859],
       [ 0.09442368],
       [ 0.49152895],
       [ 0.02579503],
       [ 0.51301915],
       [ 0.01732884],
       [ 0.05631717],
       [ 0.61246022],
       [ 0.4109829 ],
       [ 0.07604707],
       [ 0.16366653],
       [ 0.46624441],
       [ 0.08450648],
       [ 0.13670454],
       [ 0.15170034],
       [ 0.45384039],
       [ 0.07499819],
       [ 0.02705943],
       [-0.01413275],
       [ 0.13680907],
       [ 0.09513102],
       [-0.01085597],
       [ 0.20493376],
       [ 0.12001884],
       [ 0.11380386],
       [ 0.0507575 ],
       [ 0.15955743],
       [ 0.54241159],
       [ 0.23161201],
       [ 0.10466299],
       [ 0.46702201],
       [ 0.08868476],
       [ 0.47704664],
       [ 0.18510276],
       [ 0.15065822],
       [ 0.03525172],
       [ 0.18784147],
       [ 0.07994778],
       [ 0.02554128],
       [ 0.08265012],
       [ 0.17148221],
       [ 0.51861536],
       [ 0.2887361 ],
       [ 0.22293375],
       [ 0.60115465],
       [ 0.24235417],
       [ 0.06914323],
       [ 0.11612442]])

In [82]:
from sklearn.metrics import mean_absolute_error 
from sklearn.metrics import mean_squared_error 
from sklearn.metrics import median_absolute_error
import matplotlib.pyplot as plt

In [83]:
prediction_test = reg.predict(X_test)    
print(Y_test, prediction_test)
#----------------------------------------------------
#Calculating Mean Absolute Error
MAEValue = mean_absolute_error(Y_test, prediction_test, multioutput='uniform_average') # it can be raw_values
print('Mean Absolute Error Value is : ', MAEValue)

#----------------------------------------------------
#Calculating Mean Squared Error
MSEValue = mean_squared_error(Y_test, prediction_test, multioutput='uniform_average') # it can be raw_values
print('Mean Squared Error Value is : ', MSEValue)

#----------------------------------------------------
#Calculating Median Squared Error
MdSEValue = median_absolute_error(Y_test, prediction_test)
print('Median Squared Error Value is : ', MdSEValue )

[[1.57296193e-01]
 [3.91624484e-01]
 [1.35813656e-01]
 [2.24238195e-01]
 [8.37305758e-03]
 [9.93797782e-03]
 [3.28012328e-02]
 [1.30277376e-01]
 [4.63906433e-01]
 [1.22004081e-01]
 [2.31295340e-01]
 [5.35531543e-01]
 [3.44461229e-02]
 [1.43083576e-01]
 [2.85743040e-01]
 [1.30260137e-01]
 [3.38550479e-01]
 [2.87679557e-01]
 [3.25558959e-02]
 [1.72538044e-01]
 [7.47122679e-01]
 [1.39400810e-01]
 [1.77195294e-01]
 [9.42336105e-03]
 [8.84995601e-02]
 [5.29364123e-02]
 [3.53127350e-01]
 [1.60670732e-01]
 [5.63072958e-01]
 [1.10158478e-01]
 [1.18089865e-01]
 [3.77097255e-02]
 [4.75993702e-01]
 [7.30541771e-01]
 [5.16374199e-01]
 [2.16941938e-02]
 [5.27868478e-02]
 [2.13194046e-02]
 [3.29608055e-01]
 [2.21628558e-01]
 [1.75706193e-01]
 [1.97114347e-01]
 [1.47460692e-02]
 [3.33115398e-02]
 [1.88416462e-01]
 [1.05429079e-01]
 [6.83034055e-02]
 [5.49465143e-02]
 [7.11721706e-01]
 [5.81681367e-02]
 [9.30082032e-02]
 [4.21590536e-01]
 [1.32890205e-01]
 [1.45408450e-01]
 [6.95334418e-02]
 [5.31823716e-01]
 [1.04047723e-01]
 [2.10810911e-03]
 [3.97934126e-04]
 [2.74369754e-01]
 [5.38029605e-01]
 [3.29655622e-01]
 [1.54602436e-01]
 [1.29977928e-01]
 [1.14268389e-01]
 [1.46014370e-01]
 [1.47802440e-01]
 [8.97845058e-02]
 [4.53343221e-01]
 [5.82386251e-01]
 [1.38175243e-01]
 [1.90354894e-01]
 [1.86877240e-01]
 [3.18607323e-01]
 [3.15360960e-01]
 [1.56539592e-01]
 [1.30348726e-01]
 [1.83095350e-01]
 [6.52482675e-02]
 [6.71289172e-02]
 [6.11010054e-02]
 [5.33890963e-02]
 [6.93768380e-01]
 [5.78653364e-02]
 [7.57037512e-01]
 [1.86653452e-01]
 [5.49249656e-02]
 [1.02003941e-01]
 [6.14377888e-01]
 [2.49876933e-01]
 [1.99294285e-01]
 [6.16227093e-01]
 [6.51207785e-01]
 [1.29733708e-01]
 [2.25671588e-03]
 [4.57482183e-02]
 [6.78893497e-02]
 [1.03379870e-02]
 [9.31785184e-03]
 [6.63862027e-04]
 [7.25910380e-01]
 [1.39533933e-01]
 [1.96909394e-01]
 [3.62418546e-02]
 [1.74153404e-01]
 [1.31518745e-01]
 [1.83907020e-01]
 [2.56313154e-01]
 [9.80681759e-02]
 [1.34397822e-01]
 [6.82769245e-01]
 [1.72651853e-01]
 [1.46904254e-01]
 [6.39017082e-02]
 [1.66500714e-01]
 [2.56275643e-02]
 [1.16334358e-01]
 [2.81634726e-01]
 [5.04597711e-01]
 [1.96224303e-01]
 [4.47968956e-01]
 [1.51198368e-01]
 [3.73372030e-01]
 [5.39962930e-02]
 [4.39572753e-02]
 [1.41570213e-01]
 [3.41321492e-02]
 [1.36627243e-02]
 [1.75913221e-01]
 [1.51316487e-01]
 [1.77942159e-01]
 [2.97333410e-01]
 [3.92048915e-02]
 [7.59022873e-01]
 [3.27180705e-02]
 [5.66895712e-02]
 [1.47123254e-01]
 [1.62016493e-02]
 [1.98458352e-01]
 [1.39759637e-01]
 [1.37177455e-01]
 [1.18209581e-01]
 [8.18374756e-03]
 [2.54139441e-01]
 [1.05644407e-01]
 [4.71619779e-02]
 [5.99552488e-02]
 [2.73547389e-01]
 [4.83310391e-02]
 [1.66871513e-01]
 [3.04169801e-01]
 [4.55086278e-02]
 [9.61752353e-02]
 [1.04723876e-01]
 [1.00550116e-01]
 [6.58304038e-02]
 [3.78090095e-02]
 [3.39574764e-01]
 [1.00944858e-01]
 [2.42171568e-02]
 [1.66269584e-01]
 [4.68780128e-02]
 [7.75181425e-03]
 [5.59745188e-01]
 [9.06260256e-02]
 [1.42757312e-01]
 [8.26339823e-03]
 [1.66781168e-02]
 [6.80537589e-02]
 [1.85305616e-01]
 [6.43312472e-02]
 [3.50264236e-01]
 [1.39579106e-01]
 [2.50226023e-02]
 [7.27810663e-01]
 [1.10741731e-01]
 [1.88692286e-02]
 [1.75533165e-02]
 [9.90155241e-02]
 [1.57031862e-01]
 [4.36515221e-01]
 [1.63313570e-01]
 [7.18759537e-01]
 [9.93840880e-02]
 [2.04566553e-01]
 [1.86362464e-01]
 [8.58498583e-02]
 [1.05672660e-01]
 [7.20419432e-01]
 [5.34664644e-01]
 [7.19663788e-02]
 [1.90619066e-01]
 [2.10571161e-01]
 [5.84541927e-01]
 [5.93103816e-02]
 [2.84932806e-01]
 [1.92167226e-03]
 [2.56299746e-01]
 [8.51730670e-02]
 [1.52958025e-01]
 [2.11670308e-01]
 [1.75180084e-01]
 [1.28845260e-01]
 [1.62290083e-01]
 [7.73454170e-01]
 [5.74048310e-02]
 [1.69421452e-01]
 [3.12651241e-01]
 [1.64942498e-01]
 [5.83849014e-02]
 [3.94629980e-02]
 [2.09650788e-01]
 [1.72752893e-01]
 [5.58067097e-02]
 [1.59123370e-01]
 [9.14514236e-03]
 [2.64032725e-01]
 [3.99346609e-01]
 [1.63762104e-01]
 [3.72787659e-01]
 [1.51328618e-01]
 [9.15681063e-02]
 [3.31355581e-01]
 [9.55297297e-03]
 [6.05367785e-01]
 [2.03393342e-02]
 [3.12537112e-04]
 [7.61431388e-01]
 [2.39700482e-01]
 [6.55421290e-02]
 [7.32225928e-02]
 [5.70094508e-01]
 [8.10374572e-02]
 [7.52555206e-02]
 [4.58479812e-02]
 [2.96859497e-01]
 [4.98290783e-02]
 [1.81266736e-02]
 [8.08637900e-03]
 [1.30569960e-01]
 [5.28671369e-02]
 [9.82480683e-03]
 [1.68435795e-01]
 [9.14172648e-02]
 [1.18323550e-01]
 [1.43388771e-02]
 [1.69539890e-01]
 [6.38087931e-01]
 [2.03760948e-01]
 [9.12311472e-02]
 [5.94150927e-01]
 [6.93893044e-02]
 [5.85932861e-01]
 [1.48657846e-01]
 [8.66720640e-02]
 [3.56178977e-02]
 [2.21338846e-01]
 [4.50406202e-02]
 [9.89944541e-02]
 [1.44472594e-02]
 [1.11774955e-01]
 [6.27263420e-01]
 [2.30385503e-01]
 [2.07470850e-01]
 [7.33195783e-01]
 [1.34523443e-01]
 [8.15932561e-03]
 [8.74479797e-02]] [[ 0.19258687]
 [ 0.14249682]
 [ 0.16874043]
 [ 0.26996671]
 [ 0.05583164]
 [ 0.01680437]
 [ 0.01610805]
 [ 0.17216084]
 [ 0.59441419]
 [ 0.16238444]
 [ 0.24228155]
 [ 0.4441166 ]
 [ 0.03405751]
 [ 0.19215979]
 [ 0.45755453]
 [ 0.13640801]
 [ 0.49433625]
 [ 0.17793333]
 [ 0.03074942]
 [ 0.15972318]
 [ 0.60433825]
 [ 0.11343601]
 [ 0.1677746 ]
 [ 0.01922353]
 [ 0.18341015]
 [ 0.08130202]
 [ 0.50697874]
 [ 0.18656138]
 [ 0.4400924 ]
 [ 0.17455682]
 [ 0.14386894]
 [ 0.027059  ]
 [ 0.59476365]
 [ 0.59860627]
 [ 0.21801824]
 [ 0.09452994]
 [ 0.04442156]
 [-0.00244583]
 [ 0.49103   ]
 [ 0.39714886]
 [ 0.17789106]
 [ 0.2433805 ]
 [ 0.01184841]
 [ 0.00082175]
 [ 0.19559552]
 [ 0.11840518]
 [ 0.15376558]
 [ 0.07644573]
 [ 0.59101557]
 [ 0.02002698]
 [ 0.17652447]
 [ 0.55117119]
 [ 0.1431047 ]
 [ 0.1656844 ]
 [ 0.09905279]
 [ 0.41859142]
 [ 0.12971309]
 [ 0.00831718]
 [ 0.07692683]
 [ 0.42811815]
 [ 0.42051566]
 [ 0.48532064]
 [ 0.18695644]
 [ 0.0936253 ]
 [ 0.14401024]
 [ 0.18448461]
 [ 0.2050103 ]
 [ 0.11283152]
 [ 0.57417527]
 [ 0.4899653 ]
 [ 0.16604722]
 [ 0.17865966]
 [ 0.35519167]
 [ 0.4729888 ]
 [ 0.16261622]
 [ 0.18117886]
 [ 0.15810239]
 [ 0.29035102]
 [ 0.05745162]
 [ 0.10936864]
 [ 0.1246613 ]
 [ 0.09869116]
 [ 0.48150943]
 [ 0.08009735]
 [ 0.63318933]
 [ 0.17325502]
 [ 0.08158596]
 [ 0.12867763]
 [ 0.49656205]
 [ 0.42687444]
 [ 0.21618037]
 [ 0.51761941]
 [ 0.55419351]
 [ 0.14646545]
 [ 0.04465527]
 [ 0.08652798]
 [ 0.10719687]
 [ 0.02833472]
 [-0.00626737]
 [ 0.14200998]
 [ 0.59757365]
 [ 0.12972525]
 [ 0.19294106]
 [ 0.05728397]
 [ 0.12374324]
 [ 0.11681755]
 [ 0.21379068]
 [ 0.43616518]
 [ 0.16976825]
 [ 0.23632502]
 [ 0.56740247]
 [ 0.18738352]
 [ 0.21082896]
 [ 0.06643177]
 [ 0.19234263]
 [ 0.05833265]
 [ 0.14879307]
 [ 0.44369628]
 [ 0.41054683]
 [ 0.14657048]
 [ 0.19909248]
 [ 0.19106638]
 [ 0.16294786]
 [ 0.10079225]
 [ 0.12879839]
 [ 0.09574497]
 [ 0.01082059]
 [ 0.03137103]
 [ 0.15972085]
 [ 0.18374569]
 [ 0.20820367]
 [ 0.1612426 ]
 [ 0.08467196]
 [ 0.62073169]
 [ 0.07565867]
 [ 0.12935417]
 [ 0.16831223]
 [ 0.06431882]
 [ 0.21298574]
 [ 0.2007559 ]
 [ 0.14441836]
 [ 0.17847335]
 [ 0.07510918]
 [ 0.41124818]
 [ 0.17101406]
 [ 0.08405256]
 [ 0.06814408]
 [ 0.43433757]
 [ 0.08353515]
 [ 0.24921887]
 [ 0.05810977]
 [ 0.06871932]
 [ 0.08052449]
 [ 0.14984591]
 [ 0.11450491]
 [ 0.11635147]
 [ 0.08166753]
 [ 0.03636322]
 [ 0.14746366]
 [ 0.03773168]
 [ 0.26520119]
 [ 0.0931771 ]
 [-0.03065093]
 [ 0.46216126]
 [ 0.1160533 ]
 [ 0.11243293]
 [ 0.02925602]
 [ 0.06231047]
 [ 0.07746733]
 [ 0.19150688]
 [ 0.08642379]
 [ 0.50072462]
 [ 0.18171013]
 [ 0.10025542]
 [ 0.60694295]
 [ 0.13184145]
 [ 0.01425549]
 [ 0.01120815]
 [ 0.10230298]
 [ 0.2123657 ]
 [ 0.18624826]
 [ 0.18461489]
 [ 0.6006383 ]
 [ 0.14959253]
 [ 0.19233267]
 [ 0.16809191]
 [ 0.11435018]
 [ 0.11823307]
 [ 0.60484816]
 [ 0.42491369]
 [ 0.13240906]
 [ 0.26013682]
 [ 0.23394487]
 [ 0.49043981]
 [ 0.10013227]
 [ 0.45130544]
 [-0.03724102]
 [ 0.40089987]
 [ 0.11558439]
 [ 0.16315865]
 [ 0.19623308]
 [ 0.18461219]
 [ 0.09934568]
 [ 0.19907622]
 [ 0.63355965]
 [ 0.0425384 ]
 [ 0.1728464 ]
 [ 0.23765954]
 [ 0.16131605]
 [ 0.07849522]
 [ 0.02067586]
 [ 0.18215069]
 [ 0.21233206]
 [ 0.07661784]
 [ 0.22287503]
 [-0.04857142]
 [ 0.42956525]
 [ 0.13002891]
 [ 0.27871311]
 [ 0.16459969]
 [ 0.21774859]
 [ 0.09442368]
 [ 0.49152895]
 [ 0.02579503]
 [ 0.51301915]
 [ 0.01732884]
 [ 0.05631717]
 [ 0.61246022]
 [ 0.4109829 ]
 [ 0.07604707]
 [ 0.16366653]
 [ 0.46624441]
 [ 0.08450648]
 [ 0.13670454]
 [ 0.15170034]
 [ 0.45384039]
 [ 0.07499819]
 [ 0.02705943]
 [-0.01413275]
 [ 0.13680907]
 [ 0.09513102]
 [-0.01085597]
 [ 0.20493376]
 [ 0.12001884]
 [ 0.11380386]
 [ 0.0507575 ]
 [ 0.15955743]
 [ 0.54241159]
 [ 0.23161201]
 [ 0.10466299]
 [ 0.46702201]
 [ 0.08868476]
 [ 0.47704664]
 [ 0.18510276]
 [ 0.15065822]
 [ 0.03525172]
 [ 0.18784147]
 [ 0.07994778]
 [ 0.02554128]
 [ 0.08265012]
 [ 0.17148221]
 [ 0.51861536]
 [ 0.2887361 ]
 [ 0.22293375]
 [ 0.60115465]
 [ 0.24235417]
 [ 0.06914323]
 [ 0.11612442]]
Mean Absolute Error Value is :  0.06442242043952306
Mean Squared Error Value is :  0.007814568608666897
Median Squared Error Value is :  0.04135267791888135

In [84]:
#Y_test_original = scaler.inverse_transform(Y_test)
prediction_test_original = scaler.inverse_transform(prediction_test)

In [85]:
prediction_test_original

array([[13187.1597887 ],
       [10049.09033271],
       [11693.21493407],
       [18034.8953331 ],
       [ 4619.64159332],
       [ 2174.63928275],
       [ 2131.01583358],
       [11907.49879976],
       [38361.06287072],
       [11295.02152899],
       [16300.46019973],
       [28945.13519394],
       [ 3255.52366256],
       [13160.40427584],
       [29787.00250097],
       [ 9667.63544376],
       [32091.32446515],
       [12269.13661778],
       [ 3048.27708346],
       [11128.29718203],
       [38982.7912881 ],
       [ 8228.47264137],
       [11632.70696633],
       [ 2326.19646372],
       [12612.25163123],
       [ 6215.3241759 ],
       [32883.35828735],
       [12809.67189508],
       [28693.02506493],
       [12057.60346413],
       [10135.05163365],
       [ 2817.07719581],
       [38382.95606279],
       [38623.69083839],
       [14780.39858527],
       [ 7044.03433638],
       [ 3904.81702188],
       [  968.64197432],
       [31884.19238511],
       [26002.67413905],
       [12266.48873462],
       [16369.30763372],
       [ 1864.15603458],
       [ 1173.3511851 ],
       [13375.64790754],
       [ 8539.78422398],
       [10755.06234819],
       [ 5911.08478988],
       [38148.14419149],
       [ 2376.53136809],
       [12180.87360421],
       [35651.9514732 ],
       [10087.17311332],
       [11501.75935286],
       [ 7327.38439778],
       [27346.01956733],
       [ 9248.20828903],
       [ 1642.92939249],
       [ 5941.22526111],
       [27942.85582688],
       [27466.57049876],
       [31526.50896438],
       [12834.42203468],
       [ 6987.3600147 ],
       [10143.90418961],
       [12679.5652141 ],
       [13965.47006519],
       [ 8190.60227662],
       [37093.12398332],
       [31817.49038635],
       [11524.48914294],
       [12314.6403545 ],
       [23374.11677831],
       [30753.93720142],
       [11309.54185062],
       [12472.46463745],
       [11026.75729906],
       [19311.94329376],
       [ 4721.13106754],
       [ 7973.6578746 ],
       [ 8931.72111373],
       [ 7304.72928467],
       [31287.74211817],
       [ 6139.8535447 ],
       [40790.26984893],
       [11976.04757128],
       [ 6233.11263374],
       [ 9183.33849216],
       [32230.7676115 ],
       [27864.93908659],
       [14665.25890221],
       [33549.98083016],
       [35841.2950954 ],
       [10297.71933204],
       [ 3919.45850012],
       [ 6542.72344603],
       [ 7837.59968662],
       [ 2896.99930935],
       [  729.22828374],
       [10018.59082702],
       [38558.99854738],
       [ 9248.97021007],
       [13209.34932014],
       [ 4710.62815001],
       [ 8874.20585957],
       [ 8440.32103976],
       [14515.54849401],
       [28446.99018853],
       [11757.60655123],
       [15927.2923569 ],
       [36668.81757528],
       [12861.17754754],
       [14330.00066862],
       [ 5283.72444472],
       [13171.85864068],
       [ 4776.32628132],
       [10443.54175634],
       [28918.80311755],
       [26842.03755399],
       [10304.29935566],
       [13594.72710301],
       [13091.90358997],
       [11330.31868756],
       [ 7436.35923012],
       [ 9190.90343933],
       [ 7120.15440094],
       [ 1799.76441742],
       [ 3087.2197019 ],
       [11128.15117958],
       [12633.27296503],
       [14165.52994864],
       [11223.48638975],
       [ 6426.44649111],
       [40009.81646028],
       [ 5861.77699279],
       [ 9225.7224182 ],
       [11666.38867333],
       [ 5151.35148358],
       [14465.12000732],
       [13698.93810897],
       [10169.47202186],
       [12302.96866171],
       [ 5827.3522701 ],
       [26885.97624789],
       [11835.65472309],
       [ 6387.64161155],
       [ 5390.99850675],
       [28332.49301537],
       [ 6355.22659659],
       [16735.0734258 ],
       [ 4762.36315084],
       [ 5427.03666962],
       [ 6166.61339204],
       [10509.50073941],
       [ 8295.43746473],
       [ 8411.12174089],
       [ 6238.22320825],
       [ 3399.97315932],
       [10360.25591287],
       [ 3485.70511188],
       [17736.3426181 ],
       [ 6959.28105519],
       [ -798.3667745 ],
       [30075.60712795],
       [ 8392.44194182],
       [ 8165.6314576 ],
       [ 2954.71732057],
       [ 5025.53137714],
       [ 5975.08648535],
       [13119.50003531],
       [ 6536.19584253],
       [32491.54648331],
       [12505.7477538 ],
       [ 7402.72793187],
       [39145.9720762 ],
       [ 9381.54726837],
       [ 2014.95562899],
       [ 1824.04464088],
       [ 7531.00442235],
       [14426.27530567],
       [12790.05556983],
       [12687.7271745 ],
       [38750.99438721],
       [10493.6263956 ],
       [13171.23503614],
       [11652.58611619],
       [ 8285.74397629],
       [ 8529.00154933],
       [39014.73638692],
       [27742.1010134 ],
       [ 9417.10725153],
       [17419.06693046],
       [15778.17896193],
       [31847.21769605],
       [ 7395.01264777],
       [29395.50594167],
       [-1211.22650364],
       [26237.66982351],
       [ 8363.06571472],
       [11343.52423147],
       [13415.59005896],
       [12687.55793222],
       [ 7345.73403098],
       [13593.70866468],
       [40813.46955513],
       [ 3786.83929664],
       [11950.44823563],
       [16010.89777958],
       [11228.08820903],
       [ 6039.48243699],
       [ 2417.18302042],
       [12533.34853362],
       [14424.16768114],
       [ 5921.86746453],
       [15084.66947468],
       [-1921.0593341 ],
       [28033.5145408 ],
       [ 9267.99385656],
       [18582.84522065],
       [11433.8032601 ],
       [14763.50580313],
       [ 7037.3773127 ],
       [31915.45122284],
       [ 2737.89175209],
       [33261.78069576],
       [ 2207.49663954],
       [ 4650.05949857],
       [39491.62105135],
       [26869.35656531],
       [ 5886.10963639],
       [11375.34223319],
       [30331.41115275],
       [ 6416.07898937],
       [ 9686.21241395],
       [10625.67776615],
       [29554.31715956],
       [ 5820.39890704],
       [ 2817.10436473],
       [  236.47360997],
       [ 9692.76093418],
       [ 7081.69135742],
       [  441.75891724],
       [13960.67473541],
       [ 8640.87743065],
       [ 8251.51767618],
       [ 4301.75432156],
       [11117.91309803],
       [35103.17522405],
       [15632.02869485],
       [ 7678.85545974],
       [30380.12627108],
       [ 6677.84278473],
       [31008.15495496],
       [12718.29108221],
       [10560.39047328],
       [ 3330.33953606],
       [12889.86751356],
       [ 6130.48356456],
       [ 2721.99416845],
       [ 6299.78111771],
       [11864.98344214],
       [33612.37533763],
       [19210.77107566],
       [15088.34844934],
       [38783.34298876],
       [16305.00959888],
       [ 5453.59375989],
       [ 8396.89775865]])